### ISSUE TITLE
Where can I find 'srl/srl.model' model file?

### ISSUE THREAD

**Issue by targetnull** [tim5go/zhopenie#1]
Great project, but I've come across a few issues, one problem is that the `srl/srl.model` file is nowhere to be found. It is not in the BaiduCloud provided in the README file. Is this an important file, or just an option to improve the accuracy? I wonder where can I find this model file?

Thanks in advance.

**Comment by tim5go** [comment]
@targetnull  Hi, I was using version 3.3.1 when I developed it. You should find it after unzipping the file `ltp-data-v3.3.1.zip` or `ltp-data-v3.3.1.tar.bz2`
The file `srl/srl.model` is essential. You definitely need it in order to make the program work. Hope this can help you ^^

**Comment by targetnull** [comment]
I find it in version 3.3.1, thanks a lot!
