### ISSUE TITLE
加载自己的数据集出现错误

### ISSUE THREAD

**Issue by Coconut00** [tim5go/zhopenie#5]
我将example.py中引用goose得到的data去除，并替换为data=‘高克访问中国，并在同济大学发表演讲。’做测试，结果出现提示：
Python argument types in
    SementicRoleLabeller.label(SementicRoleLabeller, VectorOfString, VectorOfString, VectorOfString, VectorOfParseResult)
did not match C++ signature（此处省略很多）
并且输出为空。请问data是要什么样的格式作为输入才可以

**Comment by tim5go** [comment]
Please check #4 for the discussion
