### ISSUE TITLE
标签

### ISSUE THREAD

**Issue by CaoJonas** [tim5go/zhopenie#7]
>
 SementicRoleLabeller.label(SementicRoleLabeller, VectorOfString, VectorOfString, VectorOfString, VectorOfParseResult)
did not match C++ signature:
    label(struct SementicRoleLabeller {lvalue}, class boost::python::list, class boost::python::list, class std::vector<struct std::pair<int,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > >,class std::allocator<struct std::pair<int,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > > > 

师兄，你好，请问你有没有碰到这种情况，我在网页上也没找到相关的解决办法，师兄能不能帮忙看一下，我用的下面的环境
 pyltp ==  0.2.1 
 ltp == 3.4.0
 python3.6

**Comment by tim5go** [comment]
@CaoJonas 
You should use:
Python 2.7
ltp == 3.3.1

**Comment by CaoJonas** [comment]
谢谢
